format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$package\
$buf\
$c\
$cmake\
$cobol\
$container\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$spack\
$memory_usage\
${custom.production_check}\
$kubernetes\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[kubernetes]
format = '[k8s\($context::$namespace\)](bold green) '
disabled = false
contexts = [
{context_pattern = "gke_eflux-(?P<env>[a-z]+)_europe-west3_platform", context_alias = "$env-eu"},
]

#"kubernetes-admin@kubernetes" = "k8s@home"

[gcloud]
format = '[gcp\($project\)]($style)'
symbol = 'gcp:'

[nodejs]
disabled = true

[docker_context]
format = '[docker\($context\)]($style) '
only_with_files = false

[git_commit]
commit_hash_length = 7
only_detached = false

[directory]
use_logical_path = false

[custom.production_check]
description = "Check if current kubernetes context contains production."
command = 'cat ~/.kube/config | rg current-context | rg production > /dev/null && echo "prod->"'
shell = ["sh", "-norc"]
symbol      = ""
format      = "[$output]($style)"
style       = "red bold blink"
when        = "true"
