apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: infra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo.lab.donat.im
spec:
  type: LoadBalancer
  selector:
    name: echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
