apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns
  namespace: infra
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      containers:
        - name: ddns
          image: favonia/cloudflare-ddns:latest
          env:
            - name: CF_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: cf-token
                  name: cloudflare-credential-kk62tt79dh
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: cf-token
                  name: cloudflare-credential-kk62tt79dh
            - name: DOMAINS
              value: wan.donat.im
            - name: PROXIED
              value: "false"
            - name: IP6_PROVIDER
              value: none
