apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
nameSuffix: -s2
resources:
  - ../base-server

commonLabels:
  name: minecraft-server-s2

commonAnnotations:
  "mc-router.itzg.me/externalServerName": "s2.ms.lab.donat.im"

configMapGenerator:
  - name: extras
    files:
      - minecraft.mods.txt
  - name: minecraft-world-config
    literals:
      #- TYPE=FORGE
      - REMOVE_OLD_MODS=TRUE
      - MODE=survival
      - MOTD=Surviva - 1.20
      - SERVER_NAME=Survival 1.20
      - SEED=6280664519483202849

patches:
  - target:
      kind: Deployment
      name: minecraft-server
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minecraft-server
      spec:
        template:
          spec:
            volumes:
              - hostPath:
                  path: /kubernetes-volumes/minecraft-storage/s2
                name: minecraft-storage
