apiVersion: v1
kind: Service
metadata:
  name: minecraft-router
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "*.ms.lab.donat.im"
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      name: web
      port: 8080
    - targetPort: proxy
      name: proxy
      port: 25565
  selector:
    run: minecraft-router