apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-router-services-watcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraft-router-services-watcher
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: minecraft-router-services-watcher
subjects:
  - kind: ServiceAccount
    name: minecraft-router-services-watcher
    namespace: gaming
roleRef:
  kind: ClusterRole
  name: minecraft-router-services-watcher
  apiGroup: rbac.authorization.k8s.io
