apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: minecraft-router
  name: minecraft-router
spec:
  replicas: 1
  selector:
    matchLabels:
      run: minecraft-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: minecraft-router
    spec:
      serviceAccountName: minecraft-router-services-watcher
      containers:
      - image: itzg/mc-router:latest
        name: minecraft-router
        args: ["--api-binding", ":8080", "--in-kube-cluster"]
        ports:
        - name: proxy
          containerPort: 25565
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: 50Mi
            cpu: "100m"
          limits:
            memory: 100Mi
            cpu: "250m"