apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: plex
  name: plex
  namespace: home
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - image: plexinc/pms-docker:latest
          securityContext:
            privileged: true
          imagePullPolicy: Always
          name: plex
          ports:
            - containerPort: 32400
          env:
            - name: PLEX_CLAIM #I think this is for plex pass and you might not need it
              valueFrom:
                secretKeyRef:
                  name: plex-secret
                  key: claim
            - name: PLEX_UID
              value: "1000"
            - name: PLEX_GID
              value: "1000"
            - name: CHANGE_CONFIG_DIR_OWNERSHIP
              value: "false"
            - name: PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR
              value: "/config"
            - name: TZ
              value: "Europe/London"
            - name: ALLOWED_NETWORKS
              value: "10.0.0.0/8,192.168.0.0/20"
          livenessProbe:
            tcpSocket:
              port: 32400
          readinessProbe:
            tcpSocket:
              port: 32400
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 2000Mi
          volumeMounts:
            - mountPath: /data
              name: plex-data
            - mountPath: /config
              name: plex-config
            - mountPath: /transcode
              name: plex-transcode
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      volumes:
        - name: plex-data
          hostPath:
            path: /kubernetes-volumes/plex-storage/data
        - name: plex-config
          hostPath:
            path: /kubernetes-volumes/plex-storage/config
        - name: plex-transcode
          emptyDir: {}
