apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
resources:
- survival
- creative
- s2
- router
- flat
- "2026"


images:
  - name: itzg/minecraft-server
    newName: itzg/minecraft-server
    newTag: 2026.5.2
