apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: "gaming"
  labels:
    name: minecraft-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft.lab.donat.im
spec:
  type: LoadBalancer
  ports:
    - name: minecraft
      port: 25565
    - name: qcon
      port: 25575
    - name: map
      port: 80
      targetPort: 8080
  selector:
    name: minecraft-server