apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: "gaming"
  labels:
    app: minecraft-server
  annotations:
    external-dns.alpha.kubernetes.io/hostname: minecraft.lab.donat.im
spec:
  type: LoadBalancer
  ports:
    - port: 25565
  selector:
    app: minecraft-server