apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  namespace: "gaming"
  labels:
    name: minecraft-server
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: minecraft-server
  template:
    metadata:
      labels:
        name: minecraft-server
    spec:
      volumes:
        - name: minecraft-storage
          hostPath:
            path: /kubernetes-volumes/minecraft-storage
        - name: extras
          configMap:
            name: extras
      containers:
        - name: minecraft-server
          image: itzg/minecraft-server:2022.16.0
          resources:
            limits:
              cpu: "8000m"
              memory: 12G
            requests:
              cpu: "2000m"
              memory: 4G
          env:
            - name: TYPE
              value: "FORGE"
            - name: REMOVE_OLD_MODS
              value: "TRUE"
            - name: MODS_FILE
              value: "/extras/minecraft.mods.txt"
            - name:  EULA
              value: "TRUE"
            - name: MODE
              value: "survival"
            - name: MOTD
              value: "K8S Minecraft"
            - name: SERVER_NAME
              value: "K8S Minecraft"
            - name: PVP
              value: "false"
            - name: INIT_MEMORY
              value: 4G
            - name: MAX_MEMORY
              value: 12G
            - name: JVM_XX_OPTS
              value: "-XX:MaxRAMPercentage=75"
            - name: OVERRIDE_SERVER_PROPERTIES
              value: "true"
            - name: "SEED"
              value: "-54789620ytfrde88123"
            - name: SPAWN_PROTECTION
              value: "0"
          ports:
            - containerPort: 25565
              name: minecraft
            - containerPort: 25575
              name: qcon
            - containerPort: 8080
              name: map
          volumeMounts:
            - name: minecraft-storage
              mountPath:  /data
            - name: extras
              mountPath: /extras
          readinessProbe:
            exec:
              command:
                - mcstatus
                - 127.0.0.1
                - ping
            initialDelaySeconds: 80
            periodSeconds: 60
          livenessProbe:
            exec:
              command:
                - mcstatus
                - 127.0.0.1
                - ping
            initialDelaySeconds: 60
            periodSeconds: 60
---
