apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra
resources:
  - prometheus.configmap.yaml
  - prometheus.deployment.yaml
  - prometheus.service.yaml
  - prometheus.ingress.yaml

secretGenerator:
  - name: prometheus-ha-token
    files:
      - ha=prometheus.ha.secret
    options:
      disableNameSuffixHash: true
