apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: infra
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s
      evaluation_interval: 60s

    scrape_configs:
      - job_name: "home-assistant"
        # Replace with your Home Assistant IP/hostname
        static_configs:
          - targets: ["10.0.20.20"]
        metrics_path: /api/prometheus
        bearer_token_file: /etc/prometheus/secrets/ha
