apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: infra
spec:
  type: ClusterIP
  selector:
    name: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
