apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.13.1

resources:
  - external-dns-deployment.yaml
  - external-dns-serviceaccount.yaml
  - external-dns-clusterrole.yaml
  - external-dns-clusterrolebinding.yaml

secretGenerator:
  - name: cloudflare-credential
    files:
      - cf-token=external-dns.cf-access-token.secret