apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
resources:
  - minecraft.deployment.yaml
  - minecraft.service.yaml

configMapGenerator:
  - name: minecraft-base-config
    literals:
      - REMOVE_OLD_MODS=TRUE
      - MODS_FILE=/extras/minecraft.mods.txt
      - EULA=TRUE
      - MOTD="K8S Minecraft"
      - SERVER_NAME="K8S Minecraft"
      - PVP="false"
      - MEMORY=""
      - JVM_XX_OPTS="-XX:MaxRAMPercentage=80"
      - OVERRIDE_SERVER_PROPERTIES="true"
      - SPAWN_PROTECTION="0"
      - MAX_TICK_TIME=-1
      - ENABLE_AUTOPAUSE=TRUE
      - GUI=FALSE
      - VERSION=1.20.1
      - OPS=6f773c39-9910-4cf7-aaeb-7d50cfa21d0e,dc0ed078-8692-4fc0-9bb7-37fdc620dc8d

images:
  - name: itzg/minecraft-server
    newName: itzg/minecraft-server
    newTag: 2023.4.1

