apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: "gaming"
  labels:
    name: minecraft-server
spec:
  type: ClusterIP
  ports:
    - name: minecraft
      port: 25565
    - name: qcon
      port: 25575
    - name: map
      port: 80
      targetPort: 8080
  selector:
    name: minecraft-server