apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-lan-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.10.90-10.0.10.99
  - 10.0.10.200-10.0.10.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-lan
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-lan-pool
