apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: infra
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kibana.lab.donat.im
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5601
      protocol: TCP
  selector:
    name: kibana