apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: infra
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongo-storage
          hostPath:
            path: /kubernetes-volumes/mongo-storage
      containers:
        - name: mongo
          image: mongo:5
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet=api"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          resources:
            limits:
              cpu: 4000m
              memory: 8Gi
            requests:
              cpu: 2000m
              memory: 4Gi
