apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-ui
  namespace: infra
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: mongo-ui
  template:
    metadata:
      labels:
        name: mongo-ui
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-ui
          image: ugleiton/mongo-gui
          ports:
            - containerPort: 4321
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-internal:27017"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 200Mi
