apiVersion: v1
kind: Service
metadata:
  name: mongo-ui
  namespace: infra
  labels:
    name: mongo-ui
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mongo-ui.lab.donat.im
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4321
  selector:
    name: mongo-ui