apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
nameSuffix: -survival
resources:
  - ../base-server

commonLabels:
  name: minecraft-server-survival

commonAnnotations:
  "mc-router.itzg.me/externalServerName": "survival.ms.lab.donat.im"

configMapGenerator:
  - name: extras
    files:
      - minecraft.mods.txt
  - name: minecraft-world-config
    literals:
      - TYPE=FORGE
      - REMOVE_OLD_MODS=TRUE
      - MODE=survival
      - MOTD=Surive, will you?
      - SERVER_NAME=Donat's Survival
      - SEED=-54789620ytfrde88123

patches:
  - target:
      kind: Deployment
      name: minecraft-server
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minecraft-server
      spec:
        template:
          spec:
            volumes:
              - hostPath:
                  path: /kubernetes-volumes/minecraft-storage/survival
                name: minecraft-storage
