apiVersion: v1
kind: Service
metadata:
  name: redpanda-external
  namespace: infra
  labels:
    name: redpanda-external
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redpanda-broker.lab.donat.im
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: 19092
  selector:
    name: redpanda
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: infra
spec:
  clusterIP: None
  selector:
    name: redpanda