apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: infra
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: redpanda-console
  template:
    metadata:
      labels:
        name: redpanda-console
    spec:
      containers:
        - name: redpanda-console
          image: docker.redpanda.com/vectorized/console:v2.2.3
          env:
            - name: CONFIG_FILEPATH
              value: /config/config.yaml
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
        - name: config
          configMap:
            name: redpanda-console
