apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: infra
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: redpanda
  template:
    metadata:
      labels:
        name: redpanda
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v23.1.3
          ports:
            - containerPort: 19092
          args:
            - redpanda
            - start
            - --kafka-addr
            - internal://0.0.0.0:9092,external://0.0.0.0:19092
            - --advertise-kafka-addr
            - internal://redpanda:9092,external://redpanda-broker.lab.donat.im:9092
            - --smp
            - "1"
            - --memory 1G
            - --mode
            - dev-container
            - --default-log-level=debug
            - --pandaproxy-addr
            - internal://0.0.0.0:8082,external://0.0.0.0:18082
            - --advertise-pandaproxy-addr
            - internal://0.0.0.0:8082,external://0.0.0.0:18082
            - --rpc-addr
            - 0.0.0.0:33145
            - --advertise-rpc-addr
            -  0.0.0.0:33145
            - --set
            - redpanda.enable_idempotence=true
            - --set
            - redpanda.auto_create_topics_enabled=true
          resources:
            limits:
              cpu: 4000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 500Mi