apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik.namespace.yaml
  - traefik.serviceaccount.yaml
  - traefik.clusterrole.yaml
  - traefik.clusterrolebinding.yaml
  - traefik.ingressclass.yaml
  - traefik.deployment.yaml
  - traefik.service.yaml
