apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.10.220"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    name: traefik
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: dashboard
      port: 8080
      targetPort: dashboard
